server:
  port: 8098

spring:
  application:
    name: batch-v5
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  #disabled job run at startup
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_LOGIN}:${MONGODB_PWD}@${MONGODB_URL}/${MONGODB_DATABASE}?${MONGODB_OPTS}
      database: ${MONGODB_DATABASE}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 1000
          writetimeout: 5000
          starttls:
            enable: true
    default-encoding: UTF-8
    protocol: smtp

# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG