apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-batch-cron-job
spec:
  schedule: '10 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: spring-batch5-mongodb
              image: 'spring-batch5-mongodb:latest'
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
              resources:
                requests:
                  cpu: 500m
                  memory: 128Mi
                limits:
                  cpu: '1'
                  memory: 256Mi
              env:
                - name: MONGODB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: host
                - name: MONGODB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: database
                - name: MONGODB_OPTS
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: option
                - name: SMTP_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: smtp-host
                - name: SMTP_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: smtp-port
                - name: MONGODB_LOGIN
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: username
                - name: MONGODB_PWD
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: password
                - name: SMTP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: smtp-username
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: smtp-password

