apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # property-like keys; each key maps to a simple value
  # replace the config values with yours
  host: cluster0.xpkhnmq.mongodb.net
  database: sample_training
  option: retryWrites=true&w=majority
  smtp-host: vps-3904db98.vps.ovh.net
  smtp-port: "1025"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # replace the secret values with yours
  username: ZGJ1c2VybmFtZQ==
  password: ZGJwYXNzd29yZA==
  smtp-username: YWRtaW4=
  smtp-password: bXkgcGFzc3dvcmQ=
---
apiVersion: batch/v1
kind: Job
metadata:
  name: spring-batch-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: spring-batch5-mongodb
          image: spring-batch5-mongodb:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
          env: # array of environment variable definitions
            - name: MONGODB_URL
              valueFrom: # select individual keys in a ConfigMap
                configMapKeyRef:
                  name: app-config
                  key: host
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database
            - name: MONGODB_OPTS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: option
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: smtp-host
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: smtp-port
            - name: MONGODB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: MONGODB_PWD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: smtp-password
